### ISSUE TITLE
Something about the way trackler was packaged changed a symlink target

### ISSUE THREAD

**Issue by petertseng** [exercism/trackler#13]
As explained in #12, we would like to symlink files in the Haskell track.

As I discovered at https://github.com/exercism/xhaskell/pull/443#issuecomment-263808211, I see that currently if I `gem install trackler`, then examine `~/.gem/ruby/2.3.0/gems/trackler-2.0.3.0/tracks/haskell/exercises/pov/stack.yaml`, its symlink target is `tracks/haskell/exercises/pov/../../common/stack.yaml` instead of `../../common/stack.yaml`, the expected target as seen [in the Haskell track](https://github.com/exercism/xhaskell/blob/master/exercises/pov/stack.yaml)

The impact of this is that the file is deemed not to exist and is not served by the Exercism API, when we hoped it would be.

I tried to reproduce this by locally run `gem build trackler.gemspec`, but after `gem install` that locally-built gem it produces a target of `../../common/stack.yaml` as a target, without prepending.

So something is different, but now I don't know what because I can't reproduce it. ~~I hope it's not the case that the gem gets rewritten on upload to rubygems.org, or that the behaviour of remotely-installed gems is different in this way, since then I'll have an even harder time reproducing it.~~ I created a small gem with a symlink, pushed it to rubygems.org, then installed it from rubygems.org, and the symlink was not rewritten. So I have still failed to reproduce, unfortunately.

Can I get some help looking into this? Does `gem build trackler.gemspec` locally also change the symlink target for anyone else?

In case it is useful:

```
$ gem --version
2.5.2
```

---

Now, there have been other symlinks in other tracks, but in all those tracks the symlinks were not meant to be delivered to students - they're used in example solutions, which means it's OK if they're broken in the gem. They only need to work in a standalone checkout of the repo, which they of course do.

So this is the first time in which we are symlinking files that are meant to be delivered to the student, and if we can't figure this out, it's may be that we can't take this path.

**Comment by petertseng** [comment]
EBWODP: ~~I hope it's not the case that the gem gets rewritten on upload to rubygems.org, or that the behaviour of remotely-installed gems is different in this way, since then I'll have an even harder time reproducing it.~~

I created a small gem with a symlink, pushed it to rubygems.org, then installed it from rubygems.org, and the symlink was not rewritten. So I have still failed to reproduce, unfortunately.

**Comment by petertseng** [comment]
EBWODB

In case it is useful:

```
$ gem --version
2.5.2
```

**Comment by Insti** [comment]
I can have a look at this.

**Comment by petertseng** [comment]
Can it possibly be that it is because of https://github.com/rubygems/rubygems/pull/1457/files ?

As luck would have it, I happen to have 2.5.2, which is the first version that does have the fix according to https://github.com/rubygems/rubygems/blob/master/History.txt

I could try to test with an earlier version, if I can get an environment with an earlier version installed.

If that fmakes the difference, then we will know what to do.

**Comment by Insti** [comment]
With: 
```
$ gem --version
2.4.8
```
I don't get the symlink at all :confused: 

```
$ pwd
<snip>/gems/ruby-2.2.2@exercism/gems/trackler-2.0.3.0/tracks/haskell/exercises/pov
$ ls
examples  package.yaml  src  test
$ ls ../../common/stack.yaml 
../../common/stack.yaml
```

**Comment by Insti** [comment]
I built the trackler gem and locally installed it with rubygems version 2.4.8, which gave me a bit-identical version of `stack.yaml` in the pov directory (but not a symlink)

I suspect that using a version of rubygems > 2.5.2 is the required fix.

**Comment by Insti** [comment]
Upgraded to rubygems 2.6.8

Now I get the incorrect symlink:

`stack.yaml -> tracks/haskell/exercises/pov/../../common/stack.yaml`

**Comment by Insti** [comment]
I'm becoming more sure this is a bug in rubygems handling of relative links.
Will raise an issue there and try and work out if they think it is a feature.

**Comment by Insti** [comment]
I have a fix, just need to write the (rubygems) PR.

**Comment by kytrinyx** [comment]
Reverted https://github.com/exercism/trackler/pull/12 - but wasn't able to re-open the PR (makes sense, but now I don't know where to track it). So: tracking it here.

**Comment by Insti** [comment]
I still need to write the Rubygems PR. Thanks for the reminder.

**Comment by nilbus** [comment]
I'm pretty sure this is related… 

The exercism/exercism.io Docker container is no longer able to bundle successfully using bin/setup outside the container because of the broken symlink `fixtures/tracks/animal/exercises/fish/included-via-symlink.txt` (and others?) not playing well with mounted volumes.

```
Installing trackler 2.0.8.19
Errno::ENOENT: No such file or directory @ rb_file_s_symlink - (fixtures/tracks/animal/exercises/fish/../../.meta/include-in-fish.txt,
/exercism/vendor/bundle/ruby/2.3.0/gems/trackler-2.0.8.19/fixtures/tracks/animal/exercises/fish/included-via-symlink.txt)
An error occurred while installing trackler (2.0.8.19), and Bundler cannot continue.
Make sure that `gem install trackler -v '2.0.8.19'` succeeds before bundling.
```

Broken symlinks are just fine on the host OS (for me, OSX), and `bundle install` succeeds:

```
nilbus@hydra exercism.io $ file vendor/bundle/ruby/2.3.0/gems/trackler-2.0.8.19/fixtures/tracks/animal/exercises/fish/included-via-symlink.txt
vendor/bundle/ruby/2.3.0/gems/trackler-2.0.8.19/fixtures/tracks/animal/exercises/fish/included-via-symlink.txt: broken symbolic link to fixtures/tracks/animal/exercises/fish/../../.meta/include-in-fish.txt
```

It also bundles fine with `docker-compose build`, though unfortunately that requires reinstalling every gem.

However Docker doesn't handle it so well when using mounted volumes during development:

```
root@52d65c114d01:/exercism# file vendor/bundle/ruby/2.3.0/gems/trackler-2.0.8.19/fixtures/tracks/animal/exercises/fish/included-via-symlink.txt
vendor/bundle/ruby/2.3.0/gems/trackler-2.0.8.19/fixtures/tracks/animal/exercises/fish/included-via-symlink.txt: cannot open `vendor/bundle/ruby/2.3.0/gems/trackler-2.0.8.19/fixtures/tracks/animal/exercises/fish/included-via-symlink.txt' (No such file or directory)
root@52d65c114d01:/exercism# ls -l vendor/bundle/ruby/2.3.0/gems/trackler-2.0.8.19/fixtures/tracks/animal/exercises/fish/
ls: cannot access vendor/bundle/ruby/2.3.0/gems/trackler-2.0.8.19/fixtures/tracks/animal/exercises/fish/included-via-symlink.txt: No such file or directory
total 0
l????????? ? ? ? ?            ? included-via-symlink.txt
```

---

From reading the comments, it sounds like all this is due to a rubygems bug. @Insti Did you find that installing trackler via rubygems v2.6.5 causes the repo to have no broken symlinks?

**Comment by petertseng** [comment]
Hello, because of the presence of https://github.com/exercism/xhaskell/blob/master/exercises/pov/.dummylink and this issue, http://exercism.io/exercises/haskell/pov/readme is broken.

To reproduce, run in the root of this repo:

```
$ ruby -r./lib/trackler -e "Trackler::Tracks.new('.')['haskell'].implementations['pov'].files"
/home/pt/.rvm/gems/ruby-2.4.0/gems/trackler-2.0.8.22/lib/trackler/implementation.rb:30:in `read': No such file or directory @ rb_sysopen - tracks/haskell/exercises/pov/.dummylink (Errno::ENOENT)
```

We are grateful that http://x.exercism.io/v2/exercises/haskell/pov still works.

Of course we solve this problem by removing the dummylink file! No problem.

I just want to leave this note here so that if any track that wants to do https://github.com/exercism/x-common/issues/601 also uses a symlink and sees broken pages as a result they know how to fix it. thanks.

**Comment by petertseng** [comment]
EBWODP:

> run in the root of this repo:

Oh, sorry, obviously it will work in this repo because the repo has the correct symlinks. I meant to run it in the root of the gem install dir of trackler at an affected version (as just one example, 2.0.8.22 is affected).

**Comment by petertseng** [comment]
Somehow, 2.0.8.33 does have correct symlinks.

**Comment by petertseng** [comment]
Somehow, 2.0.8.33 does have correct symlinks. It is the first to do so; 2.0.8.32 does not have correct symlinks.

You can see this is true by running the above-mentioned command `ruby -r./lib/trackler -e "Trackler::Tracks.new('.')['haskell'].implementations['pov'].files"` in each of 2.0.8.32 and 2.0.8.33.

Since we can see that the Haskell track did not change between .33 and .32, we know the way of packaging changed to allow this to work.

**Comment by kytrinyx** [comment]
I reinstalled Ruby yesterday on the machine where I create the build artifacts. I wonder if that had something to do with this.

**Comment by kytrinyx** [comment]
(specifically, I installed it with a reference to a readline directory, which it seemed to be missing).

**Comment by petertseng** [comment]
If it result in a different version of RubyGems being used, that is a likely explanation.

We are interested in the fact that the symlink is now working, though we have doubts that we should rely on it since it has proven to be volatile in the past and we wonder if it will be a barrier to potential contributors on certain platforms. It may be that soon I will close this issue since at that point it is no longer of interest.

**Comment by petertseng** [comment]
I'm probably going to bring this upstream soon since I will stop caring about it for Exercism, but I can't yet, so for now I have to post the test script here:

```bash
tmpdir=$(mktemp -d)
# if mktemp not available on system:
#tmpdir=testgem
cd $tmpdir

mkdir dir
echo file1 > file1
echo file2 > dir/file2
ln -s ../file1 dir/link1
ln -s dir/file2 link2

if [ "$(cat dir/link1)" != "file1" ]; then
  echo "\033[1;31mSETUP WRONG, link1 doesn't contain file1\033[0m"
fi

if [ "$(cat link2)" != "file2" ]; then
  echo "\033[1;31mSETUP WRONG, link2 doesn't contain file2\033[0m"
fi

echo 'Gem::Specification.new { |s| s.name = ?a; s.version = ?1; s.summary = ?a; s.authors = ?a; s.files = %w(file1 link2 dir/link1 dir/file2) }' > a.gemspec
gem build a.gemspec
gem install a

dir=$(gem environment | grep USER | cut -d: -f2 | sed -e 's/^ *//')
adir="$dir/gems/a-1"

if [ "$(cat "$adir/dir/link1")" != "file1" ]; then
  echo "\033[1;31mINSTALLED WRONG, link1 doesn't contain file1\033[0m"
fi

if [ "$(cat "$adir/link2")" != "file2" ]; then
  echo "\033[1;31mINSTALLED WRONG, link1 doesn't contain file1\033[0m"
fi

cd ..

gem uninstall a
rm -r $tmpdir
```

**Comment by petertseng** [comment]
EBWODP:

```bash
tmpdir=$(mktemp -d)
# if mktemp not available on system:
#tmpdir=testgem
cd $tmpdir

mkdir dir
echo contents1 > file1
echo contents2 > dir/file2
ln -s ../file1 dir/link1
ln -s dir/file2 link2

if [ "$(cat dir/link1)" != "contents1" ]; then
  echo "\033[1;31mSETUP WRONG, link1 doesn't contain contents1\033[0m"
fi

if [ "$(cat link2)" != "contents2" ]; then
  echo "\033[1;31mSETUP WRONG, link2 doesn't contain contents2\033[0m"
fi

echo 'Gem::Specification.new { |s| s.name = ?a; s.version = ?1; s.summary = ?a; s.authors = ?a; s.files = %w(file1 link2 dir/link1 dir/file2) }' > a.gemspec
gem build a.gemspec
gem install a

dir=$(gem environment | grep USER | cut -d: -f2 | sed -e 's/^ *//')
adir="$dir/gems/a-1"

if [ -L "$adir/dir/link1" ]; then
  if [ "$(cat "$adir/dir/link1")" != "contents1" ]; then
    echo "\033[1;31mINSTALLED WRONG, link1 doesn't contain contents1\033[0m"
  fi
else
  echo "\033[1;31mINSTALLED WRONG, link1 doesn't exist at all\033[0m"
fi

if [ -L "$adir/link2" ]; then
  if [ "$(cat "$adir/link2")" != "contents2" ]; then
    echo "\033[1;31mINSTALLED WRONG, link2 doesn't contain contents2\033[0m"
  fi
else
  echo "\033[1;31mINSTALLED WRONG, link2 doesn't exist at all\033[0m"
fi

cd ..

gem uninstall a
rm -r $tmpdir

```
