### ISSUE TITLE
Prolog seems to be a directory instead of a submodule

### ISSUE THREAD

**Issue by mhelmetag** [exercism/trackler#2]
Not a big deal... just thought I'd point it out.

I might also be wrong. I just noticed that it was showing up in the repo languages and got confused by the amount of prolog and gnuplot up in here.

<img width="1140" alt="screen shot 2016-11-09 at 9 51 19 pm" src="https://cloud.githubusercontent.com/assets/8609429/20166061/0dd26c4e-a6c7-11e6-9951-bb65d7b92d17.png">

**Comment by tejasbubane** [comment]
The commit is https://github.com/exercism/trackler/commit/af74efbb5041b2dcf5bfd3db7ed8c340c3e9e084.
Might be the missing `.git` [here](https://github.com/exercism/trackler/blob/master/.gitmodules#L165) unlike other languages.

**Comment by mhelmetag** [comment]
That's probably it.
