### ISSUE TITLE
Display Exercise Hints Before Track Hints

### ISSUE THREAD

**Issue by lpalma** [exercism/trackler#26]
Currently, the order of the sections displayed in the exercise page is:

**Meta/Blurb**
**Description + Test Suite**
**For Bonus Points/Restrictions/Notes** (optional)
**Track Hints**
**Exercise Hints** (optional)
**Source**
**Submit Incomplete Problems**

**Track Hints** is invariant within a Track, thus students will likely read it in the first exercises but then, on following exercises, they'll ignore the rest of the page once it gets to that section.

That said, since **Exercise Hints** is specific to each exercise and not always present, they should be displayed along with optional sections, as follows:

**Meta/Blurb**
**Description + Test Suite**
**For Bonus Points/Restrictions/Notes/Exercise Hints** (optional)
**Track Hints**
**Source**
**Submit Incomplete Problems**

**Comment by Insti** [comment]
Example: http://exercism.io/exercises/haskell/beer-song/readme

**Comment by kytrinyx** [comment]
Thank you @lpalma for bringing this up. Thanks @Insti for shipping the fix!

**Comment by lpalma** [comment]
glad to help :-)
