### ISSUE TITLE
Improve signature of Track#docs method to avoid confusion

### ISSUE THREAD

**Issue by kytrinyx** [exercism/trackler#28]
This is totally my bad...

The `Track#docs` method has a confusing signature: https://github.com/exercism/trackler/blob/master/lib/trackler/track.rb#L84-L86

```
    def docs(image_path = DEFAULT_IMAGE_PATH)
      OpenStruct.new(docs_by_topic(image_path))
    end
```

This means that when it's used it looks like this:

```
track.docs("/api/v1/tracks/%s/images/docs/img" % id)
```

In order to make this more readable, I would suggest that we use a keyword argument called `:image_path`.

We would want to make it backwards-compatible until we bump trackler another major version.

**Comment by Insti** [comment]
So you want it to be able to be used as:
```ruby
track.docs(image_path: "/api/v1/tracks/%s/images/docs/img" % id)
```
?

**Comment by kytrinyx** [comment]
Yeah, I think that would be less confusing.
