### ISSUE TITLE
Add tests for unusual ignore_patterns

### ISSUE THREAD

**Issue by Insti** [exercism/trackler#36]
Now that the ignore_pattern is modifiable by the tracks there probably should be more sanity checking of the values.

Check what happens if you:

* set the ignore_pattern to ""
* make the ignore pattern an invalid regex.
* set the ignore pattern json to <some integer>,null

Any other weird things people might accidentally do?

**Comment by kytrinyx** [comment]
For weird things that people might accidentally do we should have checks in `configlet` so that it gets caught in CI rather than breaking when it gets updated in trackler.

`null` is fine. We get the default. "" is a problem. invalid regex is a problem.
