### ISSUE TITLE
What to do about an empty ignore_pattern?

### ISSUE THREAD

**Issue by Insti** [exercism/trackler#37]
Continuing discussion from: https://github.com/exercism/xgo/pull/645#issuecomment-295937672

@insti
> Ideally the track should put everything it wants ignored into the .meta directory and set ignore_pattern to ""

@petertseng 
> 
>   a track sets ignore_pattern to ""
>    there is no other special handling of ""
>
> then all paths are ignored.

@kytrinyx 
> Yeah, my assumption was that if you don't want to ignore paths, your ignore_path is not present (or is explicitly null) and you get the default. We can probably safely assume that "" means that they want the default, because ignoring all the paths seems like a pretty silly approach...

and

> I don't actually know whether to explicitly change trackler to protect tracks from defining // as the ignore path.

**Comment by Insti** [comment]
## Goal:
The goal is for a track to be able to serve all files from the implementation directory, so a human can look at what is in there and know what will be served up to the student.

Since we need some meta files, these should live in `.meta` and this directory can be ignored - we already have this feature.

If this is the case, we do not want trackler to ignore any other files in the implementation directory.

This could be achieved by setting the ignore_pattern to something like "don't ignore any other files" that hopefully will never match a filename but I think using an empty string is nicer and indicates that we're not ignoring anything.

I would like to add the code to treat an empty string as a disabled ignore_pattern.

## Spec:
The default ignore_pattern is `example`

If ignore_pattern is null or not present, use the default.
If ignore_pattern is an empty string, do not ignore any extra files.

## TODO:
[ ] Add support for empty ignore_pattern
[ ] Add support for HINTS.md in .meta

**Comment by kytrinyx** [comment]
I think this makes sense. Let's do it!
