### ISSUE TITLE
Tracks, Problems and Implementations

### ISSUE THREAD

**Issue by Insti** [exercism/trackler#40]
## Context

Definitions:

- Track - A language track.
- exercise - abstract concept for the programming exercises you do on exercism.io
- slug - short unique identifier for a problem. (e.g. 'hamming')
- Problem - An exercise as specified in the x-common repository.
- Implementation - A track-specific implementation of a problem.

With this in mind,

`track.problems` does not really make sense, it should be `track.implementations`

Most people seem to want to refer to the 'problems' belonging to a track, without having to worry about the distinction between Problems and Implementations.

However the interface of problems and implementations is different which means you still need both to get anything useful done.

Extra confusion:

exercism.io has it's own [`Problem` class](https://github.com/exercism/exercism.io/blob/master/lib/exercism/problem.rb) which is a value object combination of a track_id and a problem slug.

## Making things better

The [An `Implementation` is a `Problem`](https://github.com/exercism/trackler/pull/38) pull request takes a step towards making life better by making Implementation respond to the methods that Problem does, so you now only need a single `track.implementations` call to get all the information you need about the exercises.

But does inflict some confusion downstream by warning them that what they thought were 'problems' are actually 'implementations'

### Rename Trackler classes to match common usage.

Renaming the trackler classes will allow the intentions to be consistent across repositories, particularly with exercism.io which is probably more important since we want to make things easier for casual contributors.

'Trackler::Problem' => 'Trackler::Specification'
'Trackler::Implementation' => 'Trackler::Problem'

However doing this is likely to be super confusing, so I'd like to propose:

### 2 step solution.

Step 1:

'Trackler::Problem' => 'Trackler::ProblemSpecification'
'Trackler::Implementation' => 'Trackler::ProblemImplementation'

Deprecate 'Track.implementations' in favour of 'Track.problem_implementations'
Deprecate usage of the 'Track.problems' also in favour of 'Track.problem_implementations'
which knows everything about ProblemSpecifications anyway.

Update dependencies. (x-api, exercism.io)

Step 2: 

(n months in the future, or possibly never.)

'Trackler::ProblemSpecification' => 'Trackler::Specification'
'Trackler::ProblemImplementation' => 'Trackler::Problem'

## Discussion
Your thoughts?

**Comment by Insti** [comment]
@kytrinyx do you have any thoughts on this?
Should I just keep making PRs that push things in this direction?

**Comment by kytrinyx** [comment]
> slug - short unique identifier for a problem. (e.g. 'hamming')

For an exercise (problem or implementation)

> Problem - An exercise as specified in the x-common repository.

An exercise as specified independently of a language-specific implementation. It might be defined in the x-common repository, or it could be defined as part of an exercise that is custom to a specific track.

> Extra confusion:
> 
> exercism.io has it's own Problem class which is a value object combination of a track_id and a problem slug.

Nothing in exercism.io is the way I want it. Everything has accreted over the course of four years, and should not factor into to any of this.

> Renaming the trackler classes will allow the intentions to be consistent across repositories, particularly with exercism.io which is probably more important since we want to make things easier for casual contributors.

No. I really don't want things to be consistent with exercism.io. I want exercism.io to go away.

> 'Trackler::Problem' => 'Trackler::Specification'

That seems fine to me.

> 'Trackler::Implementation' => 'Trackler::Problem'

How about `Trackler::Exercise`?

A track has exercises that you do. Exercises are implementations of a problem specification, a.k.a. specification.

> 'Trackler::Problem' => 'Trackler::ProblemSpecification'
> 'Trackler::Implementation' => 'Trackler::ProblemImplementation'

No, I don't think this helps at all.
I'd rather go straight to something that at least makes sense internally.

**Comment by Insti** [comment]
Thanks, that is helpful.

Take 2:

Definitions:

*  Problem - abstract concept for the programming tasks you do on exercism.io.
*  Slug - A short unique identifier for a problem. (e.g. 'hamming')/ Matches `/^[a-z-]+$/`
*  Specification - Language agnostic description of a problem (They live in x-common).
*  Exercise - A language specific implementation of a specification.
*  Track - A collection of exercises implemented in the same language.
*  id - short unique identifier for a track (e.g. 'csharp'). Matches `/^[a-z-]+$/`

Todo in Trackler: 

Gradually rename Trackler classes to match intended usage:

'Trackler::Problem' => 'Trackler::Specification'
'Trackler::Implementation' => 'Trackler::Exercise'

**Comment by kytrinyx** [comment]
> Definitions [...]

Yepp, I like it. For the `slug` I would say _A short unique identifier for a problem, specification, or exercise_ since it is used at every level of abstraction.

For the todo in Trackler, I'd suggest that we:

1. Create a `Trackler::Specification` that inherits from `Trackler::Problem`
1. Update all the downstream dependencies to use it
1. Rename the `Trackler::Problem` to `Trackler::Specification` and delete the inheritance.

Likewise with Implementation -> Exercise.

**Comment by Insti** [comment]
Based on the conclusions from:  https://github.com/exercism/discussions/issues/145

Take 3

Definitions:

    Problem - abstract concept for the programming tasks you do on exercism.io.
    Exercise - An instance of a problem made up of a specification and its implementation.
    Slug - A short unique identifier for an exercise. (e.g. 'hamming')/ Matches /^[a-z-]+$/
    Specification - Language agnostic description of a problem (They live in x-common).
    Implementation - A language specific implementation of a specification.
    Track - A collection of exercises implemented in the same language.
    id - short unique identifier for a track (e.g. 'csharp'). Matches /^[a-z-]+$/

Todo in Trackler:

Gradually rename Trackler classes to match intended usage:

'Trackler::Problem' => 'Trackler::Specification'
'Trackler::Implementation' (unchanged)

Steps: 

  1. Create a Trackler::Specification that inherits from Trackler::Problem
  2. Update all the downstream dependencies to use it
  3. Rename the Trackler::Problem to Trackler::Specification and delete the inheritance.

**Comment by kytrinyx** [comment]
> Take 3

:-) I'm glad we had that conversation! I feel a lot better about the terminology that we've landed on.

**Comment by kytrinyx** [comment]
I'll go ahead and do step 1 today.

**Comment by Insti** [comment]
Todo list:

- [x] Add Trackler::Specification to replace Trackler::Problem (#57)
- [ ] Update downstream dependencies
  - [ ] exercism.io
  - [ ] x-api
- [ ] Remove references to Trackler::Problem

**Comment by kytrinyx** [comment]
Alright: final PR for this one is over in #67
