### ISSUE TITLE
Self updating tracks.

### ISSUE THREAD

**Issue by Insti** [exercism/trackler#41]
It would be nice if there was a version of trackler that could "self-update" by pulling the latest track master branches.

Although I'm not sure if part of the requirements of trackler is to serve specific fixed or guaranteed non-broken versions of the track repositories.

Inspired by: https://github.com/exercism/xgo/issues/621#issuecomment-296591862 where trackler was updated to support custom ignore patterns but the `xgo` repository changes to enable them were not included in the same trackler build.

Thoughts?

**Comment by kytrinyx** [comment]
I'm not sure I understand what you mean.

You want a trackler gem where two people might have the same version but not the same content?
