### ISSUE TITLE
Track specific exercise metadata location.

### ISSUE THREAD

**Issue by Insti** [exercism/trackler#45]
In https://github.com/exercism/xcoq/issues/7#issuecomment-300024536 @kytrinyx suggested we start a discussion about the location of the metadata files.

### Background

A track can implement problems that are not in x-common by including `metadata.yml` and `description.md` files in a `problem_slug` directory under `/exercises/`

Currently, Rust is the only track that uses these.
Coq will soon be adding some.
```
tracks/rust/exercises/luhn-from
tracks/rust/exercises/luhn-trait
```

### Proposal 

Put these files in `problem_slug/.meta` instead of in the root exercise directory.

### Rationale
In `.meta` files won't need to be explicitly ignored when serving files to students.
They are metadata so `.meta` is a more appropriate location.

### Caveats
Will require trackler changes.

cc: @exercism/rust , @exercism/coq

**Comment by petertseng** [comment]
Wow, I never really checked and therefore only just noticed that indeed, http://x.exercism.io/v2/exercises/rust/luhn-from and http://x.exercism.io/v2/exercises/rust/luhn-trait serve the description.md and metadata.yml to the students. probably shouldn't do that.

any proposal that achieves that will do

**Comment by Insti** [comment]
You should add them to your `ignore_pattern` in config.json until trackler gets updated.

**Comment by Insti** [comment]
@petertseng would you be able to **copy** the 2*2 metadata files into `.meta`?
This will enable trackler changes without having to worry about backwards compatibility.

**Comment by petertseng** [comment]
~~grumble grumble but they're not my exercises, go do it yourself or ask Ian~~

Just kidding Ian's currently limited, easy enough to do anyway
