### ISSUE TITLE
Add Implementation#language method.

### ISSUE THREAD

**Issue by Insti** [exercism/trackler#47]
An implementation should be able to report its language.

Currently you need to reach through track: `implementation.track.language`
but should be able to call: `implementation.language`

TODO: 
- [x] Add method (#54)
- [ ] Update exercism.io to use it.

**Comment by Insti** [comment]
Used here: https://github.com/exercism/exercism.io/blob/master/app/views/contribute/canonical_data.erb#L73

**Comment by kytrinyx** [comment]
Fair enough.
