### ISSUE TITLE
MASM x86 Language 

### ISSUE THREAD

**Issue by SHarber** [exercism/trackler#50]
I would like to request adding MASM x86 Assembly language to exercism.  If accepted, I would like to create several exercises for the MASM exercise repository.

**Comment by Insti** [comment]
Great @SHarber 

Go to : https://github.com/exercism/request-new-language-track read more about the process and create an issue there.

**Comment by kytrinyx** [comment]
Thanks @SHarber! I'll close this and await the new issue in request-new-language track.
