### ISSUE TITLE
Deprecate Implementation#track_id

### ISSUE THREAD

**Issue by Insti** [exercism/trackler#55]
```ruby
# DEPRECATED: We changed the class to hold on to a
# track object, however downstream dependencies send the
# to the track_id message. 
def track_id
```
https://github.com/exercism/trackler/blob/master/lib/trackler/implementation.rb#L66

Places used: (In progress - not an exhaustive list)
https://github.com/exercism/exercism.io/blob/master/app/views/languages/_contribute_exercise.erb#L24

**Comment by kytrinyx** [comment]
Deprecation warnings fail deploys. At the moment this adds a fair amount of extra work for me, as I have to go update the x-api and exercism.io repositories immediately in order to deploy.

I'd rather fix the downstream dependencies first, then deprecate (to make sure we're catching the problems).

**Comment by Insti** [comment]
>  fix the downstream dependencies first, then deprecate

This is reasonable. 👍 

I'm not 100% sure that deprecating this method is the right thing to do, but updating the dependencies will help work that out.

**Comment by kytrinyx** [comment]
> I'm not 100% sure that deprecating this method is the right thing to do, but updating the dependencies will help work that out.

That sounds like a plan!

**Comment by morrme** [comment]
Can I help with this somehow?

**Comment by Insti** [comment]
It's possibly not the easiest task one could begin with, but it would be helpful to find all the usages of Implementation#track_id in the x-api and exercism.io repositories.

Note that not all usages of `track_id` will be related to an implementation and not all instances of Implementation will be called `implementation`

**Comment by kytrinyx** [comment]
@morrme 👍 

One thing to do would be to make that method raise an error locally, and then change the Gemfile of x-api or exercism.io to point to your local version of the trackler gem instead of the one that is installed (I think Gemfiles can use `:path` to specify something on your local system). Then when you run the tests a bunch of things should blow up :-)
