### ISSUE TITLE
Add support for docs/EXERCISE_README_INSERT.org?

### ISSUE THREAD

**Issue by Insti** [exercism/trackler#64]
Tracks like xclojure have their [docs in .org format](https://github.com/exercism/xclojure/tree/master/docs)

This is supported by trackler. See: https://github.com/exercism/trackler/blob/master/lib/trackler/track.rb#L177

However this does not currently apply to the `docs/EXERCISE_README_INSERT.md` file which needs to be markdown.

Should trackler be updated to support `docs/EXERCISE_README_INSERT.org` which could be done by internally converting the .org to .md

Pros: Docs directory filetype consistency.
Cons: More complicated documentation - need to specify either .org or .md when referring to the file, more complicated parsing code.

**Comment by kytrinyx** [comment]
Hm, that's an excellent catch.

I think we should support `org`, and that if one doc file in a repo is in `org` then they should all be.

**Comment by kytrinyx** [comment]
I've experimented with generic orgmode support in #66
